services:
  servidor-ai:
    image: docker.io/ollama/ollama
    volumes:
      - vol-ollama:/root/.ollama:rw
    networks:
      - rede-cpa

  mongo:
    image: docker.io/mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    volumes:
      - vol-mongo:/data/db:rw      
    networks:
      - rede-cpa

  mongo-express:
    image: docker.io/mongo-express
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
      ME_CONFIG_MONGODB_AUTH_DATABASE: admin
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ROOT_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ROOT_PASSWORD}
      ME_CONFIG_BASICAUTH: false
    ports:
      - 8081:8081
    depends_on:
      - mongo
    networks:
      - rede-cpa

volumes: 
  vol-mongo:
  vol-ollama:

networks:
  rede-cpa: