services:
  flask-backend:
    image: quay.io/uemcpa/sistema-backend
    environment:  
      FLASK_ENV: development
    networks: 
      - rede-cpa
    
  react-frontend:
    image: quay.io/uemcpa/sistema-frontend
    ports:
      - 3000:3000
    depends_on:
      - flask-backend
    environment:
      WATCHPACK_POLLING: true
    networks: 
      - rede-cpa

  conversor-pdf-backend:
    image: quay.io/uemcpa/conversor-pdf-backend
    networks:
      - rede-cpa

  conversor-pdf-frontend:
    image: quay.io/uemcpa/conversor-pdf-frontend
    volumes:
      - conversor-pdf-frontend-data:/data:rw
    environment:
      - API_URL=http://conversor-pdf-backend:5000/upload
    ports:
      - 3001:3000
    networks:
      - rede-cpa

volumes:
  conversor-pdf-frontend-data:

networks:
  rede-cpa: