services:
  flask-backend:
    image: docker.io/uemcpa/sistema-backend
    environment:  
      FLASK_ENV: development
    networks: 
      - rede-cpa
    
  react-frontend:
    image: docker.io/uemcpa/sistema-frontend
    ports:
      - 3000:3000
    depends_on:
      - flask-backend
    environment:
      WATCHPACK_POLLING: true
    networks: 
      - rede-cpa

networks:
  rede-cpa: